spring:
  application:
    name: paytm-wallet-clone

  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: UTKARSH@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: payflow-super-secret-key-must-be-32-chars-long
  expiration-ms: 86400000

razorpay:
  key-id: rzp_test_xxxxx
  key-secret: your_secret_here
  webhook-secret: webhook_secret_here

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    com.utkarsh: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
